services:
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: 'rabbitmq:4.0.2-management-alpine'
    restart: always
    ports:
      - '${RABBITMQ_AMQP_PORT}:5672'
      - '${RABBITMQ_ADMIN_PORT}:15672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq/
      - ./rabbitmq_delayed_message_exchange-4.0.2.ez:/opt/rabbitmq/plugins/rabbitmq_delayed_message_exchange-4.0.2.ez:ro
      - ./.docker/enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
    environment:
      RABBITMQ_DEFAULT_USER: ${RMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RMQ_PASSWORD}

volumes:
  rabbitmq_log:
    driver: local
  rabbitmq_data:
    driver: local
